### ISSUE TITLE
Homebrew For Mac OSX El-Capitan

### ISSUE THREAD

**Issue by furkantasel** [ulucs/textbox#1]
There is a problem with the installation command. We should try to enhance it with keeping this in mind:

Solution to the problem:

The problem mainly occurs after updating OS X to El Capitan (OS X 10.11). This is mainly because of file permission issues with file El Capitan’s [new SIP process](http://coolestguidesontheplanet.com/what-is-sip-in-osx-10-11-el-capitan/). Try changing permissions of _/usr/local_ directory.

```
$ sudo chown -R $(whoami):admin /usr/local  
```

If it still doesn't work, use following steps and everything will be fine. This may be because homebrew is not updated.

```
1. open terminal  
2. $ cd /usr/local  
3. $ git reset --hard  
4. $ git clean -df
5. $ brew update
```

**Comment by ulucs** [comment]
Posted update with proposed fix in latest push
